### ISSUE TITLE
Two small problems about the procedure

### ISSUE THREAD

**Issue by ShenZC25** [alireza-montazeri/AV-Nash-Q-Learning#1]
Thank you very much for your outstanding work.

I have a few small questions that I want to confirm with you.

Firstly, in the `my_highway_env.py` file,
`vehicle = self.action_type.vehicle_class`
There seems to be no `color` attribute in, and it will report an error when running. 

Traceback (most recent call last):
  File "D:/PyCharm_Projects/Nash Q Learning Lane Change/AV-Nash-Q-Learning/code/train_nash_q.py", line 13, in <module>
    env = MyHighwayEnv()
  File "D:\Users\ASUS\anaconda3\envs\Nash Q Learning Lane Change\lib\site-packages\highway_env\envs\common\abstract.py", line 71, in __init__
    self.reset()
  File "D:\Users\ASUS\anaconda3\envs\Nash Q Learning Lane Change\lib\site-packages\highway_env\envs\common\abstract.py", line 205, in reset
    self._reset()
  File "D:\PyCharm_Projects\Nash Q Learning Lane Change\AV-Nash-Q-Learning\code\my_highway_env.py", line 67, in _reset
    self._create_vehicles()
  File "D:\PyCharm_Projects\Nash Q Learning Lane Change\AV-Nash-Q-Learning\code\my_highway_env.py", line 81, in _create_vehicles
    vehicle = self.action_type.vehicle_class(
TypeError: __init__() got an unexpected keyword argument 'color'

Process finished with exit code 1

However, the corresponding color attributes may be used when drawing later. Excuse me, how to solve it here?

Secondly, in the `eval_nash_q.py` file.
for _ in range(100):
     sv_action = sv.act(obs[1])

Obs[1] is passed in, which is to draw the related parameters of sv. However, it will report an error.

Traceback (most recent call last):
File "D:/PyCharm_Projects/Nash Q Learning Lane Change/AV-Nash-Q-Learning/code/eval_nash_q.py", line 43, in <module>
sv_action = sv.act(obs[1])
File "D:\PyCharm_Projects\Nash Q Learning Lane Change\AV-Nash-Q-Learning\code\surround_vehicle.py", line 6, in act
if obs[1][1] < 0.47:
KeyError: 1

And I don't understand what this 0.47 is.

How to deal with these two problems? 
Thank you for your answer.

**Comment by bfweee** [comment]
Excuse me,do you figure it out now? I have the same question.
